version: '3.8'

services:
  node:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: crud

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crud
    ports:
      - "3306:3306"
