version: '3.8'

services:
  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
    ports:
      - "3306:3306"
