version: '3.8'

services:
  node:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mariadb
    environment:
      DATABASE_HOST: mariadb
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE: crud
    command: sh -c "while ! nc -z mariadb 3306; do sleep 1; done; npm start"

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crud
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
